#!/bin/bash
currentDirectory=$HOME/.bashrc.d/
fortunesScriptFile=`find "$currentDirectory" -regex '.*fortune.*[^~]'`
fortunesScript=`cat "$fortunesScriptFile"`
alias fortunes=$fortunesScript

alias please='sudo $(history -p !-1)'
alias apt-upgrade='sudo apt-get update && sudo apt-get upgrade'
alias ll='ls -als'
alias cd..='cd ..'
alias quit=exit
alias xclip='xclip -selection c'
alias grabssh='source ~/bin/grabssh.sh'
alias batlife='upower --show-info /org/freedesktop/UPower/devices/battery_BAT0 | grep --color=no "time to \(full\|empty\)" &&  echo "     (more info with upower --dump)" || echo "     (battery full, more info with upower --dump)"'
alias cal='cal --monday'
alias emacs='emacs -nw'
alias wlan='wpa_cli status'
alias essen='__links http://www.studentenwerk-karlsruhe.de/de/mobile/canteen/?mensa=1'
