#!/bin/bash
currentDirectory=$HOME/.bashrc.d/
fortunesScriptFile=`find "$currentDirectory" -regex '.*fortune.*[^~]'`
fortunesScript=`cat "$fortunesScriptFile"`
alias fortunes=$fortunesScript

alias please='sudo $(history -p !-1)'
alias apt-upgrade='sudo apt-get update && sudo apt-get upgrade'
alias ll='ls -Alsh'
alias cd..='cd ..'
alias quit=exit
alias xclip='xclip -selection c -display :0'
alias grabssh='source ~/bin/grabssh.sh'
alias cal='cal --monday'
alias emacs='emacs -nw'
alias info='emacs -f info-standalone'
alias wlan='wpa_cli status'
alias essen='__links https://www.studentenwerk-karlsruhe.de/de/mobile/canteen/?mensa=1'
alias sus='batlife; time sudo systemctl suspend; batlife;'
alias ssh-add='ssh-add -t 1d ~/.ssh/*_rsa'

alias grep='grep --color=auto --binary-files=without-match'
alias ls='ls --color=auto'
