#!/bin/bash
export GIT_PS1_SHOWDIRTYSTATE=1                 # show dirty files with a '*' (unstaged) and a '+' (staged)
export GIT_PS1_SHOWSTASHSTATE=1                 # show stashed changes with a '$'
#export GIT_PS1_SHOWUNTRACKEDFILES=1            # show untracked files with a '%'
export GIT_PS1_SHOWUPSTREAM="git verbose"       # git: don't bother checking for an svn repository; verbose: show the number of commits ahead/behind
export GIT_PS1_DESCRIBE_STYLE="branch"          # branch: relative to newer tag or branch (master~4)
export GIT_PS1_SHOWCOLORHINTS=1                 # color the various parts of the dirty state

# if invoked with two arguments, __git_ps1 sets PS1 to "first argument" "own output" "second argument", prepending its own output with a space if there is one
TPUT_RESET="$(tput sgr0)"
TPUT_BOLD="$(tput bold)"
TPUT_GREEN="$(tput setaf 2)"
TPUT_BLUE="$(tput setaf 4)"

if [[ $HOSTNAME = lucaswerkmeister.de ]]; then
    # server has older bash whose __git_ps1 doesn't support two-argument form
    # it also doesn't supporte GIT_PS1_SHOWCOLORHINTS :(
    export PS1="\[$TPUT_RESET$TPUT_BOLD$TPUT_GREEN\]\u@\h \[$TPUT_BLUE\]\w\[$TPUT_RESET\]\$(__git_ps1 ' (%s)') \[$TPUT_BOLD$TPUT_GREEN\]\$\[$TPUT_RESET\] "
else
    export PROMPT_COMMAND='__git_ps1 "\[$TPUT_RESET$TPUT_BOLD$TPUT_GREEN\]\u@\h \[$TPUT_BLUE\]\w\[$TPUT_RESET\]" " \[$TPUT_BOLD$TPUT_GREEN\]\$\[$TPUT_RESET\] "'
fi
