#!/bin/bash

function batlife {
    chargeNow=$(</sys/class/power_supply/BAT0/charge_now)
    chargeFull=$(</sys/class/power_supply/BAT0/charge_full)
    percent=$(awk -v "chargeNow=$chargeNow" -v "chargeFull=$chargeFull" 'END { print 100 * chargeNow / chargeFull }' < /dev/null)
    LC_NUMERIC=C printf '%.2f%%\n' "$percent"

    if upower --show-info /org/freedesktop/UPower/devices/battery_BAT0 |
            grep --color=no 'time to \(full\|empty\)'; then
        prefix=''
    else
        prefix='battery full, '
    fi
        printf '    (%smore info with upower --dump)\n' "$prefix"
}
