#!/bin/bash

function lterm {
    local name=$1 location=$2
    if [[ -z $location ]]; then
        location=$HOME
        local IFS=:
        for dir in "${XDG_CONFIG_HOME:-$HOME/.config}" ${XDG_CONFIG_DIRS:-/etc/xdg}; do
            if [[ -L $dir/lterm/$name ]]; then
                location=$(readlink -- "$dir/lterm/$name")
                break
            fi
        done
    fi

    if tmux has-session -t "$name" &>/dev/null; then
        if xdotool search --name "^$name:" windowactivate &>/dev/null; then
            return
        else
            gnome-terminal --maximize -- tmux attach-session -t "$name" -c "$location"
        fi
    else
        gnome-terminal --maximize -- tmux new-session -s "$name" -c "$location"
    fi
}

function _lterm {
    if [[ $COMP_CWORD == 1 ]]; then
        COMPREPLY=()
        for dir in "${XDG_CONFIG_HOME:-$HOME/.config}" ${XDG_CONFIG_DIRS:-/etc/xdg}; do
            for link in "$dir"/lterm/*; do
                if [[ -L $link ]]; then
                    name=${link##*/}
                    if [[ $name =~ ^"$2" ]]; then
                        COMPREPLY+=("$name")
                    fi
                fi
            done
        done
    fi
}

complete -o default -o filenames -F _lterm lterm
