#!/bin/bash
# At the moment already sourced in /etc/bash_completion.d, but the
# file comment seems to indicate that this will change in the future,
# and is only kept currently to ease transitions
if [[ -f /usr/lib/git-core/git-sh-prompt ]]; then
    source /usr/lib/git-core/git-sh-prompt
fi
# In a different location on Arch linux
if [[ -f /usr/share/git/completion/git-prompt.sh ]]; then
    source /usr/share/git/completion/git-prompt.sh
fi
