#!/bin/bash

function systemd-pause {
    if (($# < 1)); then
        printf >&2 'Usage: systemd-pause UNIT...\n'
        return 1
    fi
    sudo systemctl kill --kill-who all --signal STOP -- "$@"
}
function systemd-cont {
    if (($# < 1)); then
        printf >&2 'Usage: systemd-cont UNIT...\n'
        return 1
    fi
    sudo systemctl kill --kill-who all --signal CONT -- "$@"
}
function systemd-pidof {
    if (($# != 1)); then
        printf >&2 'Usage: systemd-pidof UNIT\n'
        return 1
    fi
    local mainpid
    mainpid=$(systemctl show --property=MainPID "$1")
    mainpid=${mainpid#MainPID=}
    printf '%d\n' "$mainpid"
}

function _systemctl_kill {
    if ! type __filter_units_by_property &>/dev/null; then
        source /usr/share/bash-completion/completions/systemctl
    fi
    
    comps=$(__filter_units_by_property --system CanStop yes $(__get_active_units --system))
    COMPREPLY=($(compgen -W '$comps' -- "${COMP_WORDS[COMP_CWORD]}"))
}
complete -F _systemctl_kill systemd-pause systemd-cont systemd-pidof
