#!/bin/bash

function term {
    gnome-terminal --maximize -- "$@"
    if [[ $- == *i* ]] && ((${BASH_LINENO[-1]} == 1)); then
        # first command of an interactive shell:
        # assume this terminal was just started to launch the other terminal,
        # and now we may as well remove it
        exit
    fi
}
