#!/usr/bin/env bash

# Show the toots (posts) in one Mastodon archive.
# Usage: toots Downloads/archive-….tar.gz
# Posts are shown as a stream of concatenated JSON objects,
# automatically piped into less if stdout is a tty.

function toots {
    if (($# != 1)); then
        printf 'Usage: %s ARCHIVE\n' "${FUNCNAME[0]}"
        return 1
    fi
    if [[ $1 = *.tar.gz ]]; then
        tar -xOf "$1" outbox.json
    else
        unzip -p "$1" outbox.json
    fi | if [[ -t 1 ]]; then
        jq '.orderedItems | .[]' | less
    else
        jq '.orderedItems | .[]'
    fi
}

_xspecs[toots]='!*.@(tar.gz|zip)'
