#!/usr/bin/env bash

function wget {
    for arg; do
        if [[ $arg == '-o'* ]]; then
            printf >&2 '%s\n' \
                   'wget: you almost certainly meant -O, not -o' \
                   '(to bypass this warning, use `command wget`)'
            return 1
        fi
    done
    command wget "$@"
}
